# Generated by Django 5.2.16 on 2026-08-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyectos', '0002_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(default='img/logo.png', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=5),
        ),
    ]
